/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "awsj_proect_region":project_region,
    "aws_cognito_identity_pool_id":cognito_identity_pool_id,
    "aws_cognito_region":cognito_region,
    "aws_user_pools_id":user_pools_id,
    "aws_user_pools_web_client_id":user_pools_web_client_id,
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "productsApi",
            "endpoint": "https://tt8un1hqhc.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Product-staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
