/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    
    "aws_project_region": project_region,
    "aws_cognito_identity_pool_id": cognito_identity_pool_id,
    "aws_cognito_region": cognito_region,
    "aws_user_pools_id": user_pools_id,
    "aws_user_pools_web_client_id": user_pools_web_client_id,
    "oauth": {}
};


export default awsmobile;
